[package]
name = "kvm-csgo-cheat"
version = "0.1.0"
authors = ["Ryan McCrystal <rrmccrystal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vmread = "0.1.5"
vmread-sys = "0.1.5"
